//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HAPAccessoryKit/HAKCharacteristic.h>

#import "NSCoding.h"

@class NSArray;

@interface HAKArrayCharacteristic : HAKCharacteristic <NSCoding>
{
}

@property(copy, nonatomic) NSArray *arrayValue;
- (id)initWithCoder:(id)arg1;
- (id)initWithTypes:(id)arg1;

@end

