//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKKeychainObject.h>

@class NSArray, NSData, NSMutableArray;

@interface HAKAccessoryKeychainObject : HAKKeychainObject
{
    NSMutableArray *_controllers;
    NSData *_secretKey;
}

@property(retain, nonatomic) NSData *secretKey; // @synthesize secretKey=_secretKey;
@property(retain, nonatomic) NSArray *controllers; // @synthesize controllers=_controllers;
- (void)addController:(id)arg1;
- (void)removeControllerWithUsername:(id)arg1;
- (id)controllerWithUsername:(id)arg1;
- (id)dictionaryRepresentation;
- (id)initWithUsername:(id)arg1;
- (id)initWithDictionaryRepresentation:(id)arg1;

@end

