//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKPairingSessionDelegate.h"

@class HAKAddPairingSession, HAKPairing;

@protocol HAKAddPairingSessionDelegate <HAKPairingSessionDelegate>
- (void)addPairingSession:(HAKAddPairingSession *)arg1 didAddPairing:(HAKPairing *)arg2;
- (BOOL)controllerIsAdminForAddPairingSession:(HAKAddPairingSession *)arg1;
@end

