//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKService.h"

@class HAKIdentifyCharacteristic, HAKManufacturerCharacteristic, HAKModelCharacteristic, HAKNameCharacteristic, HAKSerialNumberCharacteristic;

@interface HAKAccessoryInformationService : HAKService
{
}

+ (id)type;
@property(readonly, nonatomic) HAKIdentifyCharacteristic *identifyCharacteristic;
@property(readonly, nonatomic) HAKSerialNumberCharacteristic *serialNumberCharacteristic;
@property(readonly, nonatomic) HAKModelCharacteristic *modelCharacteristic;
@property(readonly, nonatomic) HAKManufacturerCharacteristic *manufacturerCharacteristic;
@property(readonly, nonatomic) HAKNameCharacteristic *nameCharacteristic;
- (id)init;

@end

