//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKConnection.h"

@class CBCentral;

@interface HAKBTLEConnection : HAKConnection
{
    CBCentral *_central;
}

@property(readonly, nonatomic) CBCentral *central; // @synthesize central=_central;
- (void)handleWriteRequests:(id)arg1;
- (void)handleReadRequest:(id)arg1;
- (BOOL)encryptWithIdentifier:(id)arg1 sharedSecret:(id)arg2;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithTransport:(id)arg1 central:(id)arg2;

@end

