//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface HAKChaCha20 : NSObject
{
    struct {
        unsigned int _field1[16];
    } *_wContext;
}

+ (BOOL)isNonceValid:(id)arg1;
+ (BOOL)isKeyValid:(id)arg1;
- (id)decryptData:(id)arg1;
- (id)encryptData:(id)arg1;
- (void)dealloc;
- (id)initWithKey:(id)arg1 nonce:(id)arg2;

@end

