//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class HAKConnection;

@protocol HAKConnectionDelegate <NSObject>

@optional
- (void)connectionDidEncrypt:(HAKConnection *)arg1;
- (void)connectionDidClose:(HAKConnection *)arg1;
@end

