//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface HAKChaChaPolyData : NSObject
{
    NSData *_encryptedData;
    NSData *_authTag;
}

@property(retain) NSData *authTag; // @synthesize authTag=_authTag;
@property(retain) NSData *encryptedData; // @synthesize encryptedData=_encryptedData;
- (void).cxx_destruct;

@end

