//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@class HAKAccessoryKeychainObject, HAKKeychainKey, NSString;

@interface HAKControllerKeychainObject : NSObject
{
    NSString *_identifier;
    HAKKeychainKey *_key;
    HAKAccessoryKeychainObject *_accessoryKeychainObject;
}

@property(nonatomic) __weak HAKAccessoryKeychainObject *accessoryKeychainObject; // @synthesize accessoryKeychainObject=_accessoryKeychainObject;
@property(retain, nonatomic) HAKKeychainKey *key; // @synthesize key=_key;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithIdentifier:(id)arg1 publicKey:(id)arg2;
- (id)initWithKey:(id)arg1;

@end

