//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class HAKCharacteristic, HAKConnection;

@interface HAKCharacteristicRequest : NSObject
{
    HAKConnection *_connection;
    HAKCharacteristic *_characteristic;
}

@property(readonly, nonatomic) HAKCharacteristic *characteristic; // @synthesize characteristic=_characteristic;
@property(readonly, nonatomic) HAKConnection *connection; // @synthesize connection=_connection;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithConnection:(id)arg1 characteristic:(id)arg2;

@end

