//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import "HAKPairVerifySessionDelegate.h"

@class HAKPairingSession, HAKSecuritySession, NSString;

@interface HAKConnection : NSObject <HAKPairVerifySessionDelegate>
{
    HAKPairingSession *_pairingSession;
    HAKSecuritySession *_securitySession;
    NSObject<OS_dispatch_queue> *_workQueue;
    id <HAKPairingSessionDelegate> _pairingDelegate;
}

@property(nonatomic) __weak id <HAKPairingSessionDelegate> pairingDelegate; // @synthesize pairingDelegate=_pairingDelegate;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(readonly, nonatomic) HAKSecuritySession *securitySession; // @synthesize securitySession=_securitySession;
@property(readonly, nonatomic) HAKPairingSession *pairingSession; // @synthesize pairingSession=_pairingSession;
@property(readonly, nonatomic, getter=isEncrypted) BOOL encrypted;
- (void)pairingVerified:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

