//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKCharacteristicRequest.h"

@class NSData;

@interface HAKCharacteristicWriteRequest : HAKCharacteristicRequest
{
    BOOL _remote;
    NSData *_authorizationData;
    id _value;
}

@property(readonly, copy, nonatomic) id value; // @synthesize value=_value;
@property(readonly, nonatomic, getter=isRemote) BOOL remote; // @synthesize remote=_remote;
@property(readonly, nonatomic) NSData *authorizationData; // @synthesize authorizationData=_authorizationData;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithConnection:(id)arg1 characteristic:(id)arg2 authorizationData:(id)arg3 remote:(BOOL)arg4 value:(id)arg5;
- (id)initWithConnection:(id)arg1 characteristic:(id)arg2;

@end

