//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class HAKService, HAKUUID, NSArray, NSHashTable, NSNumber, NSString;

@interface HAKCharacteristic : NSObject <NSCoding, NSCopying>
{
    id _value;
    BOOL _readable;
    BOOL _writable;
    BOOL _updatable;
    HAKService *_service;
    HAKUUID *_UUID;
    NSNumber *_instanceID;
    NSString *_manufacturerDescription;
    unsigned long long _properties;
    unsigned long long _format;
    unsigned long long _unit;
    NSObject<OS_dispatch_queue> *_workQueue;
    NSHashTable *_subscribedConnectionsTable;
}

+ (unsigned long long)properties;
+ (id)type;
+ (id)stringForUnit:(unsigned long long)arg1;
+ (id)stringForFormat:(unsigned long long)arg1;
@property(retain, nonatomic) NSHashTable *subscribedConnectionsTable; // @synthesize subscribedConnectionsTable=_subscribedConnectionsTable;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(nonatomic, getter=isUpdatable) BOOL updatable; // @synthesize updatable=_updatable;
@property(nonatomic, getter=isWritable) BOOL writable; // @synthesize writable=_writable;
@property(nonatomic, getter=isReadable) BOOL readable; // @synthesize readable=_readable;
@property(nonatomic) unsigned long long unit; // @synthesize unit=_unit;
@property(nonatomic) unsigned long long format; // @synthesize format=_format;
@property(nonatomic) unsigned long long properties; // @synthesize properties=_properties;
@property(copy, nonatomic) NSString *manufacturerDescription; // @synthesize manufacturerDescription=_manufacturerDescription;
@property(copy, nonatomic) NSNumber *instanceID; // @synthesize instanceID=_instanceID;
@property(retain, nonatomic) HAKUUID *UUID; // @synthesize UUID=_UUID;
@property(nonatomic) HAKService *service; // @synthesize service=_service;
- (void)_handleNotifyingSubscribedConnectionsValueUpdate:(id)arg1 exceptConnection:(id)arg2;
- (void)_handleValueWrite:(id)arg1;
- (void)handleValueUpdate:(id)arg1 connection:(id)arg2;
- (BOOL)unsubscribeConnection:(id)arg1;
- (BOOL)subscribeConnection:(id)arg1;
@property(readonly, retain, nonatomic) NSArray *subscribedConnections;
@property(copy, nonatomic) id value; // @synthesize value=_value;
@property(readonly, nonatomic, getter=isNotifying) BOOL notifying;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithType:(id)arg1 properties:(unsigned long long)arg2;
- (id)init;
- (id)responseJSONObjectWithMetadata:(BOOL)arg1 properties:(BOOL)arg2 type:(BOOL)arg3 events:(BOOL)arg4;
- (id)propertiesJSONObject;
- (id)JSONObject;
- (id)transformJSONValue:(id)arg1;
- (id)JSONValue;

@end

