//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class HAKCharacteristicRequest;

@interface HAKCharacteristicResponse : NSObject
{
    BOOL _success;
    HAKCharacteristicRequest *_request;
}

@property(nonatomic) BOOL success; // @synthesize success=_success;
@property(readonly, nonatomic) HAKCharacteristicRequest *request; // @synthesize request=_request;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithRequest:(id)arg1;

@end

