//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import "HAKVersioning-Protocol.h"

@interface HAKCharacteristic : NSObject <HAKVersioning, NSCopying>
{
    BOOL _readable;
    BOOL _writable;
    BOOL _updatable;
    BOOL _notifying;
    NSArray *_types;
    id <HAKCharacteristicDelegate> _delegate;
    HAKService *_service;
    NSNumber *_instanceID;
    id _value;
    NSString *_manufacturerDescription;
    unsigned long long _format;
    unsigned long long _unit;
    NSObject<OS_dispatch_queue> *_notificationQueue;
}

+ (unsigned long long)archiveVersion;
+ (id)stringForUnit:(unsigned long long)arg1;
+ (id)stringForFormat:(unsigned long long)arg1;
+ (id)identifiers;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *notificationQueue; // @synthesize notificationQueue=_notificationQueue;
@property(nonatomic) unsigned long long unit; // @synthesize unit=_unit;
@property(nonatomic) unsigned long long format; // @synthesize format=_format;
@property(copy, nonatomic) NSString *manufacturerDescription; // @synthesize manufacturerDescription=_manufacturerDescription;
@property(nonatomic, getter=isNotifying) BOOL notifying; // @synthesize notifying=_notifying;
@property(nonatomic, getter=isUpdatable) BOOL updatable; // @synthesize updatable=_updatable;
@property(nonatomic, getter=isWritable) BOOL writable; // @synthesize writable=_writable;
@property(nonatomic, getter=isReadable) BOOL readable; // @synthesize readable=_readable;
@property(copy, nonatomic) id value; // @synthesize value=_value;
@property(copy, nonatomic) NSNumber *instanceID; // @synthesize instanceID=_instanceID;
@property(nonatomic) __weak HAKService *service; // @synthesize service=_service;
@property(nonatomic) __weak id <HAKCharacteristicDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *types; // @synthesize types=_types;
- (id)dictionaryValue;
- (id)metadataDictionaryValue;
- (id)propertiesArrayValue;
- (id)constraintsDictionaryValue;
- (void)_postCharacteristicChangeNotificationWithValue:(id)arg1;
- (BOOL)containsType:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTypes:(id)arg1;
- (id)initWithType:(id)arg1;
- (id)init;
- (id)uti;

@end

