//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface HAKCurve25519 : NSObject
{
}

+ (id)sharedKeyWithSecretKey:(id)arg1 publicKey:(id)arg2;
+ (id)publicKeyWithSecretKey:(id)arg1;
+ (id)secretKey;

@end

