//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class HAKPairing, HAKSecuritySession, HAKTransport, NSString;

@interface HAKConnection : NSObject
{
    BOOL _open;
    id <HAKConnectionDelegate> _delegate;
    HAKTransport *_transport;
    HAKPairing *_pairing;
    HAKSecuritySession *_securitySession;
}

@property(retain, nonatomic) HAKSecuritySession *securitySession; // @synthesize securitySession=_securitySession;
@property(nonatomic, getter=isOpen) BOOL open; // @synthesize open=_open;
@property(nonatomic) __weak HAKPairing *pairing; // @synthesize pairing=_pairing;
@property(readonly, nonatomic) __weak HAKTransport *transport; // @synthesize transport=_transport;
@property __weak id <HAKConnectionDelegate> delegate; // @synthesize delegate=_delegate;
- (BOOL)encryptWithIdentifier:(id)arg1 sharedSecret:(id)arg2;
- (BOOL)close;
@property(readonly, nonatomic, getter=isEncrypted) BOOL encrypted;
@property(readonly, nonatomic) NSString *identifier;
- (id)description;
- (void)dealloc;
- (id)initWithTransport:(id)arg1;

@end

