//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@interface HAKClassVersion : NSObject <NSCoding>
{
    unsigned long long _version;
    unsigned long long _miniumumSupportedVersion;
}

+ (id)classVersionWithClass:(Class)arg1;
@property(readonly, nonatomic) unsigned long long miniumumSupportedVersion; // @synthesize miniumumSupportedVersion=_miniumumSupportedVersion;
@property(readonly, nonatomic) unsigned long long version; // @synthesize version=_version;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isClassVersionSupported:(id)arg1;
- (id)description;
- (id)initWithClass:(Class)arg1;

@end

