//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class HAKUUID, HAKValueConstraints, NSString;

@interface HAKCharacteristicMetadata : NSObject
{
    HAKUUID *_type;
    NSString *_name;
    unsigned long long _properties;
    unsigned long long _permissions;
    unsigned long long _format;
    unsigned long long _unit;
    HAKValueConstraints *_constraints;
}

@property(readonly, nonatomic) HAKValueConstraints *constraints; // @synthesize constraints=_constraints;
@property(readonly, nonatomic) unsigned long long unit; // @synthesize unit=_unit;
@property(readonly, nonatomic) unsigned long long format; // @synthesize format=_format;
@property(readonly, nonatomic) unsigned long long permissions; // @synthesize permissions=_permissions;
@property(readonly, nonatomic) unsigned long long properties; // @synthesize properties=_properties;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) HAKUUID *type; // @synthesize type=_type;
- (id)description;
- (BOOL)_setUnitWithString:(id)arg1;
- (BOOL)_setFormatWithString:(id)arg1;
- (id)initWithAttributes:(id)arg1 error:(id *)arg2;

@end

