//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import "HAKVersioning.h"

@interface HAKDeprecated : NSObject <HAKVersioning>
{
}

+ (id)forwardingClassNames;
+ (unsigned long long)archiveVersion;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

