//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKCharacteristic.h"

@class NSDate;

@interface HAKDateCharacteristic : HAKCharacteristic
{
}

@property(copy, nonatomic) NSDate *dateValue;
- (id)initWithType:(id)arg1 properties:(unsigned long long)arg2;

@end

