//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HAPAccessoryKit/HAKStringCharacteristic.h>

@class NSString;

@interface HAKEndpointNameCharacteristic : HAKStringCharacteristic
{
}

+ (id)identifiers;
@property(retain, nonatomic) NSString *endpointName;
- (id)init;

@end

