//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKService.h"

@class HAKCurrentDoorStateCharacteristic, HAKLockMechanismCurrentStateCharacteristic, HAKLockMechanismTargetStateCharacteristic, HAKNameCharacteristic, HAKObstructionDetectedCharacteristic, HAKTargetDoorStateCharacteristic;

@interface HAKGarageDoorOpenerService : HAKService
{
}

+ (id)type;
@property(retain, nonatomic) HAKNameCharacteristic *nameCharacteristic;
@property(retain, nonatomic) HAKLockMechanismTargetStateCharacteristic *lockMechanismTargetStateCharacteristic;
@property(retain, nonatomic) HAKLockMechanismCurrentStateCharacteristic *lockMechanismCurrentStateCharacteristic;
@property(readonly, nonatomic) HAKObstructionDetectedCharacteristic *obstructionDetectedCharacteristic;
@property(readonly, nonatomic) HAKTargetDoorStateCharacteristic *targetDoorStateCharacteristic;
@property(readonly, nonatomic) HAKCurrentDoorStateCharacteristic *currentDoorStateCharacteristic;
- (id)init;

@end

