//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@class NSData, NSDate, NSDictionary, NSString;

@interface HAKHTTPMessage : NSObject
{
    struct __CFHTTPMessage *_message;
}

+ (id)dateFormatter;
@property(readonly) NSDate *date;
@property(readonly) NSString *contentType;
@property(readonly) unsigned long long contentLength;
- (id)serialize;
@property(readonly) NSString *version;
@property(readonly) NSData *body;
- (id)fieldValueForFieldName:(id)arg1;
@property(readonly) NSDictionary *allHeaderFields;
- (void)appendData:(id)arg1;
@property(readonly) BOOL isHeaderComplete;
- (id)description;
- (void)dealloc;
@property(readonly) NSData *tlv8Data;
@property(readonly) id JSONObject;

@end

