//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKHTTPMessage.h"

@class NSString, NSURL;

@interface HAKHTTPRequestMessage : HAKHTTPMessage
{
}

@property(readonly) BOOL isComplete;
@property(readonly) BOOL isBodyComplete;
@property(readonly) unsigned long long bodyLength;
@property(readonly) NSURL *url;
@property(readonly) NSString *method;
- (id)description;
- (id)init;

@end

