//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKHTTPMessage.h"

@class NSData, NSDate, NSString;

@interface HAKHTTPResponseMessage : HAKHTTPMessage
{
    NSString *_statusDescription;
}

@property(readonly) NSString *statusDescription; // @synthesize statusDescription=_statusDescription;
- (void)setDateToNow;
@property(retain) NSDate *date;
@property(retain) NSString *contentType;
@property unsigned long long contentLength;
- (void)setValue:(id)arg1 forHeaderField:(id)arg2;
@property(retain) NSData *body;
@property(readonly) unsigned long long statusCode;
- (id)description;
- (id)initWithStatusCode:(unsigned long long)arg1 statusDescription:(id)arg2 httpVersion:(id)arg3;
- (id)initWithStatusCode:(unsigned long long)arg1;
- (id)init;
@property(retain) id JSONObject;
@property(retain) NSData *tlv8Data;

@end

