//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKConnectionDelegate.h"

@class HAKConnection, HAKHTTPRequestMessage;

@protocol HAKIPConnectionDelegate <HAKConnectionDelegate>
- (void)connection:(HAKConnection *)arg1 didReceiveRequest:(HAKHTTPRequestMessage *)arg2;
@end

