//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@interface HAKInstanceIDPool : NSObject <NSCopying>
{
    unsigned long long _currentInstanceID;
}

+ (id)instanceIDPoolWithInstanceID:(unsigned long long)arg1;
+ (id)instanceIDPool;
@property(readonly, nonatomic) unsigned long long currentInstanceID; // @synthesize currentInstanceID=_currentInstanceID;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)instanceID;
- (id)initWithInstanceID:(unsigned long long)arg1;
- (id)init;

@end

