//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKTransport.h"
#import "HAKHTTPConnectionDelegate-Protocol.h"
#import "HAKSocketDelegate-Protocol.h"

@class HAKNetService, HAKSocket, NSMutableArray, NSNumber, NSThread;

@interface HAKIPTransport : HAKTransport <NSCoding, NSNetServiceDelegate, HAKHTTPConnectionDelegate, HAKSocketDelegate>
{
    BOOL _serverThreadShouldRun;
    HAKSocket *_socket;
    HAKNetService *_netService;
    NSMutableArray *_connections;
    NSThread *_serverThread;
    NSNumber *_configurationNumber;
    NSNumber *_stateNumber;
}

@property BOOL serverThreadShouldRun; // @synthesize serverThreadShouldRun=_serverThreadShouldRun;
@property(retain, nonatomic) NSNumber *stateNumber; // @synthesize stateNumber=_stateNumber;
@property(retain, nonatomic) NSNumber *configurationNumber; // @synthesize configurationNumber=_configurationNumber;
@property(retain, nonatomic) NSThread *serverThread; // @synthesize serverThread=_serverThread;
@property(retain, nonatomic) NSMutableArray *connections; // @synthesize connections=_connections;
@property(retain, nonatomic) HAKNetService *netService; // @synthesize netService=_netService;
@property(retain, nonatomic) HAKSocket *socket; // @synthesize socket=_socket;
- (void)serverThreadMain;
- (void)removeSources;
- (id)handleCharacteristicRequest:(id)arg1;
- (id)handleAllCharacteristicsRequestWithService:(id)arg1;
- (id)handleServiceRequest:(id)arg1;
- (id)handleAllServicesRequestForAccessory:(id)arg1;
- (id)handleAllAccessoriesRequest;
- (id)postRequestWithURL:(id)arg1 contentType:(id)arg2 body:(id)arg3;
- (id)deleteRequestWithURL:(id)arg1 contentType:(id)arg2 body:(id)arg3;
- (id)putRequestWithURL:(id)arg1 contentType:(id)arg2 body:(id)arg3;
- (id)getRequestWithURL:(id)arg1;
- (void)identify;
- (id)primaryAccessory;
@property(readonly, nonatomic) unsigned long long port;
- (void)removeAccessory:(id)arg1;
- (void)addAccessory:(id)arg1;
- (void)stop;
- (void)start;
- (void)setUsername:(id)arg1;
- (void)netServiceDidStop:(id)arg1;
- (void)netService:(id)arg1 didNotPublish:(id)arg2;
- (void)netServiceDidPublish:(id)arg1;
- (void)newConnectionWithInputStream:(id)arg1 outputStream:(id)arg2;
- (BOOL)connectionShouldClose:(id)arg1;
- (id)receivedRequest:(id)arg1;
- (void)accessory:(id)arg1 didUpdateValue:(id)arg2 forCharacteristic:(id)arg3;
- (void)accessory:(id)arg1 didUpdateService:(id)arg2;
- (void)accessory:(id)arg1 didRemoveService:(id)arg2;
- (void)accessory:(id)arg1 didAddService:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

