//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKConnection.h"

#import "NSStreamDelegate.h"

@class HAKHTTPRequestMessage, HAKSecuritySessionPacket, NSHost, NSInputStream, NSOutputStream, NSString;

@interface HAKIPConnection : HAKConnection <NSStreamDelegate>
{
    NSInputStream *_inputStream;
    NSOutputStream *_outputStream;
    NSHost *_host;
    NSObject<OS_dispatch_queue> *_workQueue;
    HAKSecuritySessionPacket *_currentPacket;
    HAKHTTPRequestMessage *_currentRequest;
}

@property(retain, nonatomic) HAKHTTPRequestMessage *currentRequest; // @synthesize currentRequest=_currentRequest;
@property(retain, nonatomic) HAKSecuritySessionPacket *currentPacket; // @synthesize currentPacket=_currentPacket;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(readonly, nonatomic) NSHost *host; // @synthesize host=_host;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (void)_handleIncomingData:(id)arg1;
- (void)_handleHTTPRequestData:(id)arg1 encrypted:(BOOL)arg2;
- (void)sendResponseMessage:(id)arg1;
- (void)_sendResponseData:(id)arg1 encrypt:(BOOL)arg2;
- (BOOL)close;
- (BOOL)open;
- (BOOL)encryptWithIdentifier:(id)arg1 sharedSecret:(id)arg2;
@property(readonly, copy) NSString *description;
- (id)initWithTransport:(id)arg1 host:(id)arg2 inputStream:(id)arg3 outputStream:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

