//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKTransport.h"

#import "HAKIPConnectionDelegate.h"
#import "HAKSocketDelegate.h"

@class HAKNetService, HAKSocket, NSString, NSThread;

@interface HAKIPTransport : HAKTransport <NSCoding, NSNetServiceDelegate, HAKIPConnectionDelegate, HAKSocketDelegate>
{
    BOOL _dirty;
    BOOL _serverThreadShouldRun;
    HAKSocket *_socket;
    HAKNetService *_netService;
    NSThread *_serverThread;
}

+ (unsigned long long)httpResponseCodeWithReadResponseStatus:(long long)arg1;
+ (unsigned long long)httpResponseCodeWithWriteResponseStatus:(long long)arg1;
+ (long long)ipErrorCodeWithReadResponseStatus:(long long)arg1;
+ (long long)ipErrorCodeWithWriteResponseStatus:(long long)arg1;
+ (unsigned long long)maxSupportedAccessories;
@property BOOL serverThreadShouldRun; // @synthesize serverThreadShouldRun=_serverThreadShouldRun;
@property(getter=isDirty) BOOL dirty; // @synthesize dirty=_dirty;
@property(retain, nonatomic) NSThread *serverThread; // @synthesize serverThread=_serverThread;
@property(retain, nonatomic) HAKNetService *netService; // @synthesize netService=_netService;
@property(retain, nonatomic) HAKSocket *socket; // @synthesize socket=_socket;
- (void)serverThreadMain;
- (void)removeSources;
- (id)_characteristicWriteWithConnection:(id)arg1 request:(id)arg2 characteristicWriteRequests:(id)arg3 attributes:(id)arg4 error:(char *)arg5;
- (void)_handleCharacteristicWriteWithConnection:(id)arg1 request:(id)arg2;
- (void)_handleCharacteristicReadRequest:(id)arg1;
- (void)_handleAllAccessoriesRequestWithConnection:(id)arg1 request:(id)arg2;
- (void)_postRequestWithConnection:(id)arg1 request:(id)arg2;
- (void)_putRequestWithConnection:(id)arg1 request:(id)arg2;
- (void)_getRequestWithConnection:(id)arg1 request:(id)arg2;
- (void)identifyWithConnection:(id)arg1 request:(id)arg2;
@property(readonly, nonatomic) unsigned long long port;
- (BOOL)updateValue:(id)arg1 forCharacteristic:(id)arg2 onSubscribedConnections:(id)arg3;
- (void)stop;
- (void)start;
- (void)setPaired:(BOOL)arg1;
- (void)setStateNumber:(id)arg1;
- (void)setConfigurationNumber:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (unsigned long long)type;
- (void)netServiceDidStop:(id)arg1;
- (void)netService:(id)arg1 didNotPublish:(id)arg2;
- (void)netServiceDidPublish:(id)arg1;
- (void)newConnectionWithHost:(id)arg1 inputStream:(id)arg2 outputStream:(id)arg3;
- (void)connection:(id)arg1 didReceiveRequest:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

