//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKCharacteristicReadRequest.h"

@interface HAKIPCharacteristicReadRequest : HAKCharacteristicReadRequest
{
    BOOL _metadata;
    BOOL _permissions;
    BOOL _format;
    BOOL _notify;
}

@property(readonly, nonatomic) BOOL notify; // @synthesize notify=_notify;
@property(readonly, nonatomic) BOOL format; // @synthesize format=_format;
@property(readonly, nonatomic) BOOL permissions; // @synthesize permissions=_permissions;
@property(readonly, nonatomic) BOOL metadata; // @synthesize metadata=_metadata;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithConnection:(id)arg1 characteristic:(id)arg2 metadata:(BOOL)arg3 permissions:(BOOL)arg4 format:(BOOL)arg5 notify:(BOOL)arg6;

@end

