//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKNumberCharacteristic.h"

@interface HAKIntegerCharacteristic : HAKNumberCharacteristic <NSCoding>
{
}

@property(nonatomic) long long integerValue;
- (id)initWithCoder:(id)arg1;
- (id)initWithTypes:(id)arg1;

@end

