//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface HAKKeychainService : NSObject
{
    NSMutableDictionary *_rootObject;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)keychainFileURL;
+ (id)defaultKeychainService;
@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)addAccessory:(id)arg1;
- (id)accessoryWithUsername:(id)arg1;
- (id)allAccessories;
- (void)setRootObject:(id)arg1;
- (id)rootObject;
- (void)removeAllAccessories;
- (id)init;

@end

