//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKService.h"

@class HAKLockMechanismCurrentStateCharacteristic, HAKLockMechanismTargetStateCharacteristic, HAKNameCharacteristic;

@interface HAKLockMechanismService : HAKService
{
}

+ (id)type;
@property(retain, nonatomic) HAKNameCharacteristic *nameCharacteristic;
@property(readonly, nonatomic) HAKLockMechanismTargetStateCharacteristic *targetLockMechanismStateCharacteristic;
@property(readonly, nonatomic) HAKLockMechanismCurrentStateCharacteristic *currentLockMechanismStateCharacteristic;
- (id)init;

@end

