//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKService.h"

@class HAKAdministratorOnlyAccessCharacteristic, HAKCurrentDoorStateCharacteristic, HAKLockManagementAutoSecureTimeoutCharacteristic, HAKLockManagementControlPointCharacteristic, HAKLockMechanismLastKnownActionCharacteristic, HAKLogsCharacteristic, HAKMotionDetectedCharacteristic, HAKNameCharacteristic, HAKVersionCharacteristic;

@interface HAKLockManagementService : HAKService
{
}

+ (id)type;
@property(retain, nonatomic) HAKNameCharacteristic *nameCharacteristic;
@property(retain, nonatomic) HAKMotionDetectedCharacteristic *motionDetectedCharacteristic;
@property(retain, nonatomic) HAKCurrentDoorStateCharacteristic *currentDoorStateCharacteristic;
@property(retain, nonatomic) HAKLockMechanismLastKnownActionCharacteristic *lockMechanismLastKnownActionCharacteristic;
@property(retain, nonatomic) HAKAdministratorOnlyAccessCharacteristic *administratorOnlyAccessCharacteristic;
@property(retain, nonatomic) HAKLockManagementAutoSecureTimeoutCharacteristic *lockManagementAutoSecureTimeoutCharacteristic;
@property(retain, nonatomic) HAKLogsCharacteristic *logsCharacteristic;
@property(readonly, nonatomic) HAKVersionCharacteristic *versionCharacteristic;
@property(readonly, nonatomic) HAKLockManagementControlPointCharacteristic *lockManagementControlPointCharacteristic;
- (id)init;

@end

