//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKTLV8Characteristic.h"

@class NSDate;

@interface HAKLockManagementControlPointCharacteristic : HAKTLV8Characteristic
{
}

+ (unsigned long long)properties;
+ (id)type;
@property(readonly, nonatomic) NSDate *currentTime;
@property(readonly, nonatomic) BOOL clearLogs;
@property(readonly, nonatomic) NSDate *logStartTime;

@end

