//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class NSArray;

@interface HAKMetadata : NSObject
{
    NSArray *_characteristics;
    NSArray *_services;
}

+ (BOOL)isValidMetadataWithURL:(id)arg1 error:(id *)arg2;
+ (id)defaultMetadata;
@property(readonly, nonatomic) NSArray *services; // @synthesize services=_services;
@property(readonly, nonatomic) NSArray *characteristics; // @synthesize characteristics=_characteristics;
- (id)serviceMetadataWithType:(id)arg1;
- (id)characteristicMetadataWithType:(id)arg1;
- (BOOL)_parseServicesWithServiceMetadata:(id)arg1 error:(id *)arg2;
- (BOOL)_parseCharacteristicsWithCharacteristicMetdata:(id)arg1 error:(id *)arg2;
- (BOOL)_parseMetadata:(id)arg1 error:(id *)arg2;
- (id)initWithURL:(id)arg1 error:(id *)arg2;

@end

