//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class HAKMetadata;

@interface HAKMetadataService : NSObject
{
    HAKMetadata *_metadata;
    NSObject<OS_dispatch_queue> *_workQueue;
}

+ (id)defaultMetadataService;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(retain, nonatomic) HAKMetadata *metadata;
- (id)init;

@end

