//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNetService.h"

@class NSString;

@interface HAKNetService : NSNetService
{
    NSObject<OS_dispatch_queue> *_txtRecordQueue;
}

+ (id)defaultTXTRecord;
+ (id)generateUniqueMACAddress;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *txtRecordQueue; // @synthesize txtRecordQueue=_txtRecordQueue;
@property(nonatomic) unsigned char statusOptions;
- (void)incrementStateNumber;
@property(nonatomic) unsigned short stateNumber;
@property(retain, nonatomic) NSString *protocolVersion;
@property(retain, nonatomic) NSString *modelName;
@property(retain, nonatomic) NSString *identifier;
@property(nonatomic) unsigned char featureOptions;
- (void)incrementConfigurationNumber;
@property(nonatomic) unsigned short configurationNumber;
- (id)txtRecordValueForKey:(id)arg1;
- (void)setTXTRecordValue:(id)arg1 forKey:(id)arg2;
- (void)setTXTRecord:(id)arg1;
- (id)txtRecord;
- (id)initWithName:(id)arg1 port:(unsigned long long)arg2;

@end

