//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKValueConstraints.h"

@class NSNumber;

@interface HAKNumberConstraints : HAKValueConstraints
{
    NSNumber *_minimumValue;
    NSNumber *_maximumValue;
    NSNumber *_stepValue;
}

@property(copy, nonatomic) NSNumber *stepValue; // @synthesize stepValue=_stepValue;
@property(readonly, copy, nonatomic) NSNumber *maximumValue; // @synthesize maximumValue=_maximumValue;
@property(readonly, copy, nonatomic) NSNumber *minimumValue; // @synthesize minimumValue=_minimumValue;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)validateValue:(id)arg1;
- (id)description;
- (id)initWithMinimumValue:(id)arg1 maximumValue:(id)arg2;
- (id)init;
- (id)attributes;

@end

