//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HAPAccessoryKit/HAKBoolCharacteristic.h>

@interface HAKObstructionDetectedCharacteristic : HAKBoolCharacteristic
{
}

+ (id)identifiers;
@property(nonatomic, getter=isObstructed) BOOL obstructionDetected;
- (id)init;

@end

