//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKBoolCharacteristic.h"

@interface HAKObstructionDetectedCharacteristic : HAKBoolCharacteristic
{
}

+ (unsigned long long)properties;
+ (id)type;
@property(nonatomic, getter=isObstructed) BOOL obstructionDetected;
- (id)init;

@end

