//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKCharacteristic.h"

#import "HAKPairingSessionDelegate.h"

@class NSMapTable, NSString;

@interface HAKPairingCharacteristic : HAKCharacteristic <HAKPairingSessionDelegate>
{
    NSMapTable *_connections;
    NSObject<OS_dispatch_queue> *_connectionsQ;
}

+ (long long)writeResponseStatusWithPairingSessionStatus:(long long)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *connectionsQ; // @synthesize connectionsQ=_connectionsQ;
@property(retain, nonatomic) NSMapTable *connections; // @synthesize connections=_connections;
- (id)handleWriteRequest:(id)arg1;
- (id)handleReadRequest:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)value;
- (id)identifierForPairingSession:(id)arg1;
- (void)removePairingSessionForConnection:(id)arg1;
- (void)setPairingSession:(id)arg1 forConnection:(id)arg2;
- (id)pairingSessionForConnection:(id)arg1;
- (id)connectionForPairingSession:(id)arg1;
- (id)initWithType:(id)arg1 properties:(unsigned long long)arg2 format:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

