//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKPairingCharacteristic.h"

#import "HAKPairVerifySessionDelegate.h"

@class NSString;

@interface HAKPairVerifyCharacteristic : HAKPairingCharacteristic <HAKPairVerifySessionDelegate>
{
}

+ (id)pairVerifyCharacteristic;
- (id)handleReadRequest:(id)arg1;
- (id)handleWriteRequest:(id)arg1;
- (void)pairVerifySession:(id)arg1 verifiedPairingWithIdentifier:(id)arg2 sharedSecret:(id)arg3;
- (id)initWithType:(id)arg1 properties:(unsigned long long)arg2 format:(unsigned long long)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

