//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@class HAKPairSetupSession, HAKPairVerifySession;

@interface HAKPairingSession : NSObject
{
    HAKPairSetupSession *_pairSetupSession;
    HAKPairVerifySession *_pairVerifySession;
    id <HAKPairingSessionDelegate> _pairingDelegate;
}

@property(nonatomic) __weak id <HAKPairingSessionDelegate> pairingDelegate; // @synthesize pairingDelegate=_pairingDelegate;
@property(readonly, nonatomic) HAKPairVerifySession *pairVerifySession; // @synthesize pairVerifySession=_pairVerifySession;
- (id)handlePairVerify:(id)arg1;
- (id)handlePairSetup:(id)arg1;
- (id)init;

@end

