//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface HAKPairSetupSession : NSObject
{
    struct srp_st *_session;
    NSData *_salt;
    NSData *_publicKey;
    NSData *_secretKey;
    unsigned char _state;
    NSString *_username;
    NSString *_password;
    id <HAKPairingSessionDelegate> _delegate;
}

@property __weak id <HAKPairingSessionDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(readonly, nonatomic) struct srp_st *session; // @synthesize session=_session;
@property(readonly, nonatomic) unsigned char state; // @synthesize state=_state;
@property(readonly, nonatomic) NSData *secretKey; // @synthesize secretKey=_secretKey;
- (void).cxx_destruct;
- (id)handlePairSetup:(id)arg1;
- (id)proofResponseWithClientProof:(id)arg1;
- (id)generateSecretKeyWithPublicKey:(id)arg1;
@property(readonly, nonatomic) NSData *publicKey; // @synthesize publicKey=_publicKey;
@property(readonly, nonatomic) NSData *salt; // @synthesize salt=_salt;
- (id)init;

@end

