//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKPairingSession.h"

@class HAKAccessoryKeychainObject, HAKTLV8Container, NSData;

@interface HAKPairVerifySession : HAKPairingSession
{
    unsigned char _state;
    id <HAKPairVerifySessionDelegate> _delegate;
    NSData *_publicKey;
    NSData *_sharedSecret;
    HAKAccessoryKeychainObject *_accessoryKeychain;
    NSData *_controllerPublicKey;
    NSData *_sessionKey;
    HAKTLV8Container *_stateData;
}

@property(retain, nonatomic) HAKTLV8Container *stateData; // @synthesize stateData=_stateData;
@property(nonatomic) unsigned char state; // @synthesize state=_state;
@property(retain, nonatomic) NSData *sessionKey; // @synthesize sessionKey=_sessionKey;
@property(retain, nonatomic) NSData *controllerPublicKey; // @synthesize controllerPublicKey=_controllerPublicKey;
@property(retain, nonatomic) HAKAccessoryKeychainObject *accessoryKeychain; // @synthesize accessoryKeychain=_accessoryKeychain;
@property(retain, nonatomic) NSData *sharedSecret; // @synthesize sharedSecret=_sharedSecret;
@property(retain, nonatomic) NSData *publicKey; // @synthesize publicKey=_publicKey;
@property __weak id <HAKPairVerifySessionDelegate> delegate; // @synthesize delegate=_delegate;
- (id)handlePairingSessionReadRequest;
- (long long)handlePairingSessionWriteRequest:(id)arg1;
- (void)_resetState;
- (id)_tlv8ResponseWithError:(unsigned char)arg1;
- (id)init;

@end

