//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKPairingCharacteristic.h"

#import "HAKPairSetupSessionDelegate.h"

@class HAKConnection, HAKPairSetupSession, NSString;

@interface HAKPairSetupCharacteristic : HAKPairingCharacteristic <HAKPairSetupSessionDelegate>
{
    HAKConnection *_currentConnection;
    HAKPairSetupSession *_pairSetupSession;
    NSObject<OS_dispatch_queue> *_pairSetupQueue;
}

+ (id)pairSetupCharacteristic;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *pairSetupQueue; // @synthesize pairSetupQueue=_pairSetupQueue;
@property(retain, nonatomic) HAKPairSetupSession *pairSetupSession; // @synthesize pairSetupSession=_pairSetupSession;
@property(nonatomic) __weak HAKConnection *currentConnection; // @synthesize currentConnection=_currentConnection;
- (void)pairSetupSession:(id)arg1 didAddPairing:(id)arg2;
- (id)handleReadRequest:(id)arg1;
- (id)handleWriteRequest:(id)arg1;
- (id)passwordForPairSetupSession:(id)arg1;
- (id)identifierForPairingSession:(id)arg1;
- (id)initWithType:(id)arg1 properties:(unsigned long long)arg2 format:(unsigned long long)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

