//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKPairingSessionDelegate.h"

@class HAKPairSetupSession, HAKPairing, NSString;

@protocol HAKPairSetupSessionDelegate <HAKPairingSessionDelegate>

@optional
- (void)pairSetupSession:(HAKPairSetupSession *)arg1 didAddPairing:(HAKPairing *)arg2;
- (NSString *)passwordForPairSetupSession:(HAKPairSetupSession *)arg1;
@end

