//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface HAKPoly1305 : NSObject
{
    struct poly1305_context *_pContext;
}

+ (BOOL)isKeyValid:(id)arg1;
- (id)tag;
- (void)updateWithData:(id)arg1;
- (void)dealloc;
- (id)initWithKey:(id)arg1;

@end

