//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKPairingSession.h"

@class HAKTLV8Container;

@interface HAKRemovePairingSession : HAKPairingSession
{
    unsigned char _state;
    id <HAKRemovePairingSessionDelegate> _delegate;
    HAKTLV8Container *_stateData;
}

@property(retain, nonatomic) HAKTLV8Container *stateData; // @synthesize stateData=_stateData;
@property(nonatomic) unsigned char state; // @synthesize state=_state;
@property __weak id <HAKRemovePairingSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (id)handlePairingSessionReadRequest;
- (long long)handlePairingSessionWriteRequest:(id)arg1;
- (void)_lockSession;
- (id)_tlv8ResponseWithError:(unsigned char)arg1;
- (id)init;

@end

