//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class NSHost, NSInputStream, NSOutputStream;

@protocol HAKSocketDelegate <NSObject>
- (void)newConnectionWithHost:(NSHost *)arg1 inputStream:(NSInputStream *)arg2 outputStream:(NSOutputStream *)arg3;
@end

