//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

#import "HAKCharacteristicDelegate-Protocol.h"
#import "HAKVersioning-Protocol.h"

@class HAKAccessory;

@interface HAKService : NSObject <HAKCharacteristicDelegate, HAKVersioning, NSCopying>
{
    NSMutableOrderedSet *_characteristics;
    NSArray *_types;
    id <HAKServiceDelegate> _delegate;
    HAKAccessory *_accessory;
    NSNumber *_instanceID;
    unsigned long long _characteristicInstanceID;
    NSObject<OS_dispatch_queue> *_notificationQueue;
}

+ (unsigned long long)archiveVersion;
+ (id)identifiers;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *notificationQueue; // @synthesize notificationQueue=_notificationQueue;
@property(nonatomic) unsigned long long characteristicInstanceID; // @synthesize characteristicInstanceID=_characteristicInstanceID;
@property(copy, nonatomic) NSNumber *instanceID; // @synthesize instanceID=_instanceID;
@property(nonatomic) __weak HAKAccessory *accessory; // @synthesize accessory=_accessory;
@property(nonatomic) __weak id <HAKServiceDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSOrderedSet *characteristics; // @synthesize characteristics=_characteristics;
@property(readonly, nonatomic) NSArray *types; // @synthesize types=_types;
- (id)characteristicWithTypes:(id)arg1;
- (id)characteristicWithType:(id)arg1;
- (id)characteristicWithInstanceId:(unsigned long long)arg1;
- (void)removeAllCharacteristicsWithTypes:(id)arg1;
- (void)removeAllCharacteristicsWithType:(id)arg1;
- (void)removeCharacteristic:(id)arg1;
- (void)addCharacteristic:(id)arg1;
- (id)dictionaryValue;
- (BOOL)containsType:(id)arg1;
- (void)characteristic:(id)arg1 didUpdateValue:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTypes:(id)arg1;
- (id)initWithType:(id)arg1;
- (id)init;
- (id)uti;

@end

