//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@class NSData, NSMutableData;

@interface HAKSecuritySessionPacket : NSObject
{
    NSMutableData *_encryptedData;
    NSMutableData *_authTag;
    BOOL _complete;
    unsigned long long _length;
}

@property(nonatomic) unsigned long long length; // @synthesize length=_length;
@property(nonatomic, getter=isComplete) BOOL complete; // @synthesize complete=_complete;
@property(readonly, nonatomic) NSData *authTag; // @synthesize authTag=_authTag;
@property(readonly, nonatomic) NSData *encryptedData; // @synthesize encryptedData=_encryptedData;
- (id)chaChaPolyData;
- (long long)appendData:(id)arg1;
- (id)init;

@end

