//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKStringCharacteristic.h"

@class NSString;

@interface HAKSerialNumberCharacteristic : HAKStringCharacteristic
{
}

+ (unsigned long long)properties;
+ (id)type;
@property(retain) NSString *serialNumber;
- (id)init;

@end

