//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@class NSData;

@interface HAKSecuritySession : NSObject
{
    NSData *_accessoryToControllerKey;
    unsigned long long _accessoryToControllerCount;
    NSData *_controllerToAccessoryKey;
    unsigned long long _controllerToAccessoryCount;
}

- (id)decryptPacket:(id)arg1;
- (id)encryptData:(id)arg1;
- (id)initWithSharedSecret:(id)arg1;

@end

