//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import Foundation;

@class HAKUUID, NSArray, NSString;

@interface HAKServiceMetadata : NSObject
{
    BOOL _primary;
    HAKUUID *_type;
    HAKUUID *_ipUUID;
    HAKUUID *_btleUUID;
    NSString *_name;
    NSArray *_requiredCharacteristics;
    NSArray *_optionalCharacteristics;
    NSArray *_includedServices;
}

@property(readonly, nonatomic) NSArray *includedServices; // @synthesize includedServices=_includedServices;
@property(readonly, nonatomic) NSArray *optionalCharacteristics; // @synthesize optionalCharacteristics=_optionalCharacteristics;
@property(readonly, nonatomic) NSArray *requiredCharacteristics; // @synthesize requiredCharacteristics=_requiredCharacteristics;
@property(readonly, nonatomic, getter=isPrimary) BOOL primary; // @synthesize primary=_primary;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) HAKUUID *btleUUID; // @synthesize btleUUID=_btleUUID;
@property(readonly, nonatomic) HAKUUID *ipUUID; // @synthesize ipUUID=_ipUUID;
@property(readonly, nonatomic) HAKUUID *type; // @synthesize type=_type;
- (id)description;
- (id)initWithAttributes:(id)arg1 characteristics:(id)arg2 error:(id *)arg3;

@end

