//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKValueConstraints.h"

@class NSNumber;

@interface HAKStringConstraints : HAKValueConstraints
{
    NSNumber *_maximumLength;
}

@property(copy, nonatomic) NSNumber *maximumLength; // @synthesize maximumLength=_maximumLength;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)validateValue:(id)arg1;
- (id)description;
- (id)initWithMaximumLength:(id)arg1;
- (id)init;
- (id)attributes;

@end

