//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HAPAccessoryKit/HAKService.h>

#import "HAKVersioning.h"

@class HAKCoolingThresholdTemperatureCharacteristic, HAKCurrentHeatingCoolingModeCharacteristic, HAKCurrentRelativeHumidityCharacteristic, HAKCurrentTemperatureCharacteristic, HAKHeatingThresholdTemperatureCharacteristic, HAKNameCharacteristic, HAKTargetHeatingCoolingModeCharacteristic, HAKTargetRelativeHumidityCharacteristic, HAKTargetTemperatureCharacteristic, HAKTemperatureUnitsCharacteristic;

@interface HAKThermostatService : HAKService <HAKVersioning>
{
    HAKHeatingThresholdTemperatureCharacteristic *_heatingThresholdTemperatureCharacteristic;
    HAKCoolingThresholdTemperatureCharacteristic *_coolingThresholdTemperatureCharacteristic;
}

+ (unsigned long long)archiveVersion;
+ (id)identifiers;
@property(retain, nonatomic) HAKCoolingThresholdTemperatureCharacteristic *coolingThresholdTemperatureCharacteristic; // @synthesize coolingThresholdTemperatureCharacteristic=_coolingThresholdTemperatureCharacteristic;
@property(retain, nonatomic) HAKHeatingThresholdTemperatureCharacteristic *heatingThresholdTemperatureCharacteristic; // @synthesize heatingThresholdTemperatureCharacteristic=_heatingThresholdTemperatureCharacteristic;
- (void).cxx_destruct;
@property(retain, nonatomic) HAKNameCharacteristic *nameCharacteristic;
- (id)coolingThresholdTemperature;
- (id)heatingThresholdTemperature;
@property(retain, nonatomic) HAKTargetRelativeHumidityCharacteristic *targetRelativeHumidityCharacteristic;
@property(retain, nonatomic) HAKCurrentRelativeHumidityCharacteristic *currentRelativeHumidityCharacteristic;
@property(readonly, nonatomic) HAKTemperatureUnitsCharacteristic *temperatureUnitsCharacteristic;
@property(readonly, nonatomic) HAKTargetTemperatureCharacteristic *targetTemperatureCharacteristic;
@property(readonly, nonatomic) HAKCurrentTemperatureCharacteristic *currentTemperatureCharacteristic;
@property(readonly, nonatomic) HAKTargetHeatingCoolingModeCharacteristic *targetHeatingCoolingModeCharacteristic;
@property(readonly, nonatomic) HAKCurrentHeatingCoolingModeCharacteristic *currentHeatingCoolingModeCharacteristic;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

