//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKUnsignedCharCharacteristic.h"

@interface HAKTargetDoorStateCharacteristic : HAKUnsignedCharCharacteristic
{
}

+ (unsigned long long)properties;
+ (id)type;
@property(nonatomic) unsigned char targetDoorState;
- (id)init;

@end

