//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import "HAKAccessoryDelegate.h"
#import "HAKPairingSessionDelegate.h"

@class HAKInstanceIDPool, HAKTransportManager, NSArray, NSMutableArray, NSString;

@interface HAKTransport : NSObject <NSCopying, NSCoding, HAKPairingSessionDelegate, HAKAccessoryDelegate>
{
    NSMutableArray *_accessories;
    BOOL _started;
    NSString *_password;
    NSString *_name;
    NSString *_identifier;
    HAKTransportManager *_transportManager;
    HAKInstanceIDPool *_instanceIDPool;
    NSObject<OS_dispatch_queue> *_workQueue;
}

+ (id)restrictedPasswordSet;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(retain, nonatomic) HAKInstanceIDPool *instanceIDPool; // @synthesize instanceIDPool=_instanceIDPool;
@property(nonatomic) __weak HAKTransportManager *transportManager; // @synthesize transportManager=_transportManager;
@property(retain, nonatomic) NSArray *accessories; // @synthesize accessories=_accessories;
- (id)accessoryWithInstanceID:(unsigned long long)arg1;
- (void)removeAccessory:(id)arg1;
- (void)addAccessory:(id)arg1;
@property(nonatomic, getter=isStarted) BOOL started; // @synthesize started=_started;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (BOOL)updateValue:(id)arg1 forCharacteristic:(id)arg2 onSubscribedConnections:(id)arg3;
- (void)stop;
- (void)start;
- (void)_setPassword:(id)arg1;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
- (void)accessory:(id)arg1 didUpdateValue:(id)arg2 forCharacteristic:(id)arg3;
- (void)accessory:(id)arg1 didUpdateService:(id)arg2;
- (void)accessory:(id)arg1 didRemoveService:(id)arg2;
- (void)accessory:(id)arg1 didAddService:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

