//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HAPAccessoryKit/HAKFloatCharacteristic.h>

#import "HAKVersioning.h"

@interface HAKTargetTemperatureCharacteristic : HAKFloatCharacteristic <HAKVersioning>
{
}

+ (unsigned long long)archiveVersion;
+ (id)identifiers;
@property(nonatomic) float targetTemperature;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

