//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <HAPAccessoryKit/HAKTypeIdentifier.h>

@class NSString;

@interface HAKUTI : HAKTypeIdentifier
{
}

@property(readonly, copy, nonatomic) NSString *uti;
- (id)initWithUTIString:(id)arg1;
- (id)init;

@end

