//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HAKNumberCharacteristic.h"

@interface HAKUnsignedLongCharacteristic : HAKNumberCharacteristic
{
}

@property(nonatomic) unsigned long long unsignedLongValue;
- (id)initWithType:(id)arg1 properties:(unsigned long long)arg2;

@end

