//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSKeyedUnarchiver.h"

#import "NSKeyedUnarchiverDelegate.h"

@class NSString;

@interface HAKVersionedUnarchiver : NSKeyedUnarchiver <NSKeyedUnarchiverDelegate>
{
    id <NSKeyedUnarchiverDelegate> _relayDelegate;
}

+ (id)forwardingClassTable;
@property(nonatomic) __weak id <NSKeyedUnarchiverDelegate> relayDelegate; // @synthesize relayDelegate=_relayDelegate;
- (void)_setClassVersions;
- (void)_registerForwardingClasses;
- (id)initForReadingWithData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

