//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (HAKChaChaPoly)
+ (id)dataWithUint64:(unsigned long long)arg1;
+ (id)dataWithUint32:(unsigned int)arg1;
+ (id)dataWithUint16:(unsigned short)arg1;
- (unsigned long long)uint64Value;
- (unsigned int)uint32Value;
- (unsigned short)uint16Value;
- (id)initWithUint64:(unsigned long long)arg1;
- (id)initWithUint32:(unsigned int)arg1;
- (id)initWithUint16:(unsigned short)arg1;
@end

