//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSError.h"

@interface NSError (HAKError)
+ (id)errorWithCode:(long long)arg1 description:(id)arg2 suggestion:(id)arg3;
+ (id)errorWithCode:(long long)arg1 description:(id)arg2;
@end

