//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSObject (Runtime)
+ (void)enumerateClassListUsingBlock:(CDUnknownBlockType)arg1;
+ (BOOL)implementsClassMethod:(SEL)arg1;
+ (BOOL)implementsInstanceMethod:(SEL)arg1;
@end

